version: '2'

volumes:
    sense-data:
    dashboard-data:

  services:

    serialmodbus2mqtt:
      build: ./serialmodbus2mqtt
      privileged: true
      environment:
        MODBUS_HOST_IP: '192.168.1.132'
        MODBUS_HOST_PORT: '10502'
        MQTT_BROKER_IP: '127.0.0.1'
        MQTT_BROKER_PORT: '1883'
        MODBUS_POLLING_SECS: '5'
        REG_INSTANT_FLOW: 1
        LENGTH_INSTANT_FLOW: 2
      network_mode: host
      devices:
        - "/dev/ttySC0:/dev/ttySC0"
      restart: "no"

  influxdb:
    restart: always
    image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
    volumes:
      - 'sense-data:/var/lib/influxdb'

  dashboard:
    image: balenablocks/dashboard
    restart: always
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'

  connector:
    build: ./connector
    restart: always
    labels:
      io.balena.features.balena-api: '1'
    privileged: true
    ports:
      - "8080"

  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
    restart: always    
    
  smartmeterprocessor:
    build: ./smartmeterprocessor
    network_mode: host
    environment:
      MQTT_BROKER_IP: '127.0.0.1'
      MQTT_BROKER_PORT: '1883'
